name: share_sphere_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  flutter_signin_button: ^2.0.0
  flutter_spinkit: ^5.2.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  provider: ^6.0.5
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  image_gallery_saver: ^2.0.3
  video_player: ^2.6.0
  chewie: ^1.4.0
  share_plus: ^6.3.1
  flutter_native_api: ^0.0.1
  video_thumbnail: ^0.5.3
  file_manager: ^1.0.1
  file_picker: ^5.2.7
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: plugins.justsoft.xyz/video_thumbnail
        pluginClass: VideoThumbnailPlugin
      ios:
        pluginClass: VideoThumbnailPlugin

  uses-material-design: true

  assets:
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
